CREATE TABLE [dbo].[TradeOffers] (
    [Id]           INT          IDENTITY (1, 1) NOT NULL,
    [SenderName]   VARCHAR (32) NOT NULL,
    [ReceiverName] VARCHAR (32) NOT NULL,
    [WoodSender] INT          NOT NULL DEFAULT 0,
    [ClaySender]        INT          NOT NULL DEFAULT 0,
    [WoolSender]    INT          NOT NULL DEFAULT 0,
    [StoneSender]        INT          NOT NULL DEFAULT 0,
	[IronSender] INT NOT NULL DEFAULT 0, 
	[StrawSender] INT NOT NULL DEFAULT 0, 
	[FoodSender] INT NOT NULL DEFAULT 0, 
	[GoldSender] INT NOT NULL DEFAULT 0,
	[WoodReceiver] INT NOT NULL DEFAULT 0,
	[ClayReceiver] INT NOT NULL DEFAULT 0, 
	[WoolReceiver] INT NOT NULL DEFAULT 0, 
	[StoneReceiver] INT NOT NULL DEFAULT 0, 
	[IronReceiver] INT NOT NULL DEFAULT 0, 
	[StrawReceiver] INT NOT NULL DEFAULT 0, 
	[FoodReceiver] INT NOT NULL DEFAULT 0, 
	[GoldReceiver] INT NOT NULL DEFAULT 0, 
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TradeOffers_Players_1] FOREIGN KEY ([ReceiverName]) REFERENCES [dbo].[Players] ([Name]),
    CONSTRAINT [FK_TradeOffers_Players] FOREIGN KEY ([SenderName]) REFERENCES [dbo].[Players] ([Name]),
    CONSTRAINT [CK_TradeOffers_WoodSender_NotNegative] CHECK ([WoodSender] >= (0)),
    CONSTRAINT [CK_TradeOffers_ClaySender_NotNegative] CHECK ([ClaySender] >= (0)),
    CONSTRAINT [CK_TradeOffers_StoneSender_NotNegative] CHECK ([StoneSender] >= (0)),
    CONSTRAINT [CK_TradeOffers_WoolSender_NotNegative] CHECK ([WoolSender] >= (0)),
	CONSTRAINT [CK_TradeOffers_IronSender_NotNegative] CHECK ([IronSender] >= 0),
	CONSTRAINT [CK_TradeOffers_StrawSender_NotNegative] CHECK ([StrawSender] >= 0),
	CONSTRAINT [CK_TradeOffers_FoodSender_NotNegative] CHECK ([FoodSender] >= 0),
	CONSTRAINT [CK_TradeOffers_GoldSender_NotNegative] CHECK ([GoldSender] >= 0), 
	CONSTRAINT [CK_TradeOffers_WoodReceiver_NotNegative] CHECK ([WoodReceiver] >= 0), 
	CONSTRAINT [CK_TradeOffers_ClayReceiver_NotNegative] CHECK ([ClayReceiver] >= 0), 
	CONSTRAINT [CK_TradeOffers_WoolReceiver_NotNegative] CHECK ([WoolReceiver] >= 0), 
	CONSTRAINT [CK_TradeOffers_StoneReceiver_NotNegative] CHECK ([StoneReceiver] >= 0), 
	CONSTRAINT [CK_TradeOffers_IronReceiver_NotNegative] CHECK ([IronReceiver] >= 0), 
	CONSTRAINT [CK_TradeOffers_StrawReceiver_NotNegative] CHECK ([StrawReceiver] >= 0), 
	CONSTRAINT [CK_TradeOffers_FoodReceiver_NotNegative] CHECK ([FoodReceiver] >= 0), 
	CONSTRAINT [CK_TradeOffers_GoldReceiver_NotNegative] CHECK ([GoldReceiver] >= 0),
    CONSTRAINT [CK_TradeOffers] CHECK ([SenderName] <> [ReceiverName])
);

